networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  db_data:
  wp_data:
  minio_data:

services:
  # --- DATABASE LAYER ---
  db:
    image: mariadb:10.11
    container_name: wp_enterprise_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-net

  # --- CACHING LAYER ---
  redis:
    image: redis:7-alpine
    container_name: wp_enterprise_redis
    restart: always
    networks:
      - backend-net

  # --- OBJECT STORAGE LAYER (S3 Simulator) ---
  minio:
    image: quay.io/minio/minio:latest
    container_name: wp_enterprise_minio
    restart: always
    # KODE DIBAWAH INI MEMAKSA MINIO UNTUK OTOMATIS MEMBUAT BUCKET DAN MEMBUATNYA PUBLIC
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' & 
      until curl -s http://localhost:9000/minio/health/live; do sleep 1; done;
      mc alias set myminio http://localhost:9000 minioadmin minioadminpassword;
      mc mb myminio/wordpress-uploads || true;
      mc anonymous set public myminio/wordpress-uploads;
      wait"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - frontend-net
      - backend-net

  # --- APPLICATION LAYER ---
  wordpress:
    image: wordpress:latest
    container_name: wp_enterprise_app
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - db
      - redis
      - minio